language: python

python:
  - "3.5"

sudo: false

env:
    - TOX_ENV=py33-django18-drf31
    - TOX_ENV=py33-django18-drf32
    - TOX_ENV=py33-django18-drf33
    - TOX_ENV=py34-django18-drf31
    - TOX_ENV=py34-django18-drf32
    - TOX_ENV=py34-django18-drf33
    - TOX_ENV=py35-django18-drf31
    - TOX_ENV=py35-django18-drf32
    - TOX_ENV=py35-django18-drf33
    - TOX_ENV=py34-django19-drf31
    - TOX_ENV=py34-django19-drf32
    - TOX_ENV=py34-django19-drf33
    - TOX_ENV=py35-django19-drf31
    - TOX_ENV=py35-django19-drf32
    - TOX_ENV=py35-django19-drf33

matrix:
  fast_finish: true

install:
  # Virtualenv < 14 is required to keep the Python 3.2 builds running.
  - pip install tox "virtualenv<14"

script:
    - tox -e $TOX_ENV
